project:
  type: website
  output-dir: docs

website:
  title: "WYBORY SAMORZĄDOWE 2024      ANDRZEJ KOPEĆ - KILKA SŁÓW O MNIE"
  navbar:
    left:
      - text: " "
        file: index.qmd
  sidebar:
    style: "docked"
    search: true
    
format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

