project:
  type: website
  output-dir: docs

website:
  title: "ANDRZEJ KOPEĆ WYBORY SAMORZĄDOWE 2024"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - omnie.qmd
  sidebar:
    style: "docked"
    search: true
    
format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

