project:
  type: website
  output-dir: docs

website:
  title: "ANDRZEJ KOPEĆ WYBORY SAMORZĄDOWE 2024"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - omnie.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Basics"
        contents:
          - index.qmd
      - section: "Layout"
        contents:
          - omnie.qml
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

