project:
  type: website
  output-dir: docs

website:
  title: "ANDRZEJ KOPEĆ WYBORY SAMORZĄDOWE 2024       STRONA INFORMACYJNA"
  navbar:
    left:
      - text: " "
        file: index.qmd
  sidebar:
    style: "docked"
    search: true
    
format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

